// <auto-generated />
using DeudoresApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeudoresApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeudoresApi.Domain.Models.Deudor", b =>
                {
                    b.Property<string>("NroIdentificacion")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("SituacionMaxima")
                        .HasColumnType("integer");

                    b.Property<decimal>("SumaTotalPrestamos")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("NroIdentificacion");

                    b.ToTable("Deudores");
                });

            modelBuilder.Entity("DeudoresApi.Domain.Models.Entidad", b =>
                {
                    b.Property<string>("CodigoEntidad")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<decimal>("SumaTotalPrestamos")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("CodigoEntidad");

                    b.ToTable("Entidades");
                });
#pragma warning restore 612, 618
        }
    }
}
